apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.6.4"
dependencies:
- name: metrics-server
  repository: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.11.0